name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: docker build . -t cartesi/toolchain
      
      - run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - run: |
          docker tag cartesi/toolchain cartesi/toolchain:${GITHUB_REF:11}
          docker push cartesi/toolchain:${GITHUB_REF:11}
        if: startsWith(github.ref, 'refs/tags/v')
      
      - run: docker push cartesi/toolchain
        if: github.ref == 'refs/heads/master'
